### ISSUE TITLE
Layout error

### ISSUE THREAD

**Issue by muresanandrei** [jacklein/rn-bottom-drawer#10]
I get Malformed calls from JS:field sizes are different. Tried everything from issues still the same no matter what I do.

**Comment by wfilleman** [comment]
I'm seeing the same thing. This is working in production apps on 0.56, but just upgraded to the latest RN 0.59.3 and I'm seeing this error as well. Haven't been able to find the line that's causing it yet.

Any ideas?

**Comment by Jacklol** [comment]
i have this problem too

**Comment by jacklein** [comment]
Fixed this issue in #12

**Comment by wfilleman** [comment]
@jacklein Thank you! Works great.
