### ISSUE TITLE
toggle the drawer state

### ISSUE THREAD

**Issue by FelipeCorerato** [jacklein/rn-bottom-drawer#11]
hello! is there any way to change the drawer's mode (opened to closed/closed to opened) by a button or touchable opacity?

**Comment by jacklein** [comment]
Not currently but that is a nice feature. I will work on it or anyone else can put a PR in.

**Comment by matinzd** [comment]
> Not currently but that is a nice feature. I will work on it or anyone else can put a PR in.



> hello! is there any way to change the drawer's mode (opened to closed/closed to opened) by a button or touchable opacity?

Its on the way and I created pull request

**Comment by FelipeCorerato** [comment]
wow thank you @matinzd !! can you notify me when the request is approved?

**Comment by GwnElviin** [comment]
Would be nice if this gets implemented, really want to add functionality to a button so i can open/close the drawer

**Comment by matinzd** [comment]
> Would be nice if this gets implemented, really want to add functionality to a button so i can open/close the drawer

Fork my repo and use it

**Comment by GwnElviin** [comment]
> > Would be nice if this gets implemented, really want to add functionality to a button so i can open/close the drawer
> 
> Fork my repo and use it

I forked your repo but i dont know how to use it.
Would you mind posting an example?
@matinzd

**Comment by matinzd** [comment]
> > > Would be nice if this gets implemented, really want to add functionality to a button so i can open/close the drawer
> > 
> > 
> > Fork my repo and use it
> 
> I forked your repo but i dont know how to use it.
> Would you mind posting an example?
> @matinzd

Just create reference from component and then use these methods as you want .. 
```
 <BottomDawer ref={ref => this.drawer = ref} />

  this.drawer.setDrawerState(state) // Can be accessed by BottomDrawer.DOWN_STATE or BottomDrawer.UP_STATE

  this.drawer.toggleDrawerState()

  this.drawer.openBottomDrawer() 

  this.drawer.closeBottomDrawer()
```

**Comment by ansarikhurshid786** [comment]
@matinzd thanks i will check your repository.

**Comment by ansarikhurshid786** [comment]
@matinzd No, it is not working. i am getting error  - toggleDrawerState or other all function is undefined.

**Comment by matinzd** [comment]
> @matinzd No, it is not working. i am getting error - toggleDrawerState or other all function is undefined.

Please provide me your code

**Comment by ansarikhurshid786** [comment]
```
<View>
   <Text style={{color:"red"}}> Welcome to React Native! </Text>
   <Button onPress={()=>{
         this.drawer.closeBottomDrawer();
      }} title="Toggle" />
      <BottomDrawer ref={ (ref)=> this.drawer = ref} containerHeight={200} offset={49}>
         <Text> Get directions to your location </Text>
      </BottomDrawer>
</View>
```

**Comment by nomanmakh098** [comment]
i am having the same issue as above

**Comment by alanupstone** [comment]
Hello. Did anyone have any luck? I am using the great bit if code within a functional component not a class, so 'this' can't be used. Thanks.

**Comment by rishav95** [comment]
If anyone is still looking for alternatives for this library, since this one seems to have been abandoned

https://github.com/osdnk/react-native-reanimated-bottom-sheet

this one works pretty well and provides a lot more control
