### ISSUE TITLE
iPhone X

### ISSUE THREAD

**Issue by tronze** [jacklein/rn-bottom-drawer#24]
How do I calculate the offset (or give a option) to drawer on iPhone X and above versions?
It is rendering the drawer view ignoring the safe area, so the drawer is positioned lower than usual. Is there any options for iPhone X and above versions to position the drawer properly?

**Comment by mqtik** [comment]
Have you tried this?
https://www.npmjs.com/package/react-native-iphone-x-helper

**Comment by tronze** [comment]
> Have you tried this?
> https://www.npmjs.com/package/react-native-iphone-x-helper

Thanks for your reply!
I already used other libraries to handle bottom drawer part.

Thanks for your help.

**Comment by mqtik** [comment]
@tronze what did you use? (i'm curious)
