### ISSUE TITLE
useNativeDriver required

### ISSUE THREAD

**Issue by NTakemori** [jacklein/rn-bottom-drawer#39]
Error: "Animated: `useNativeDriver` was not specified. This is a required option and must be explicitly set to `true` or `false`"

**Comment by NTakemori** [comment]
For anyone that wants to fix this, go to the Animator and add the useNativeDriver: true then fix the styling for the Animated.View from {...this.position.getLayout(), left: 0} to {transform: [{translateY: this.position.y}]}

**Comment by prettydev** [comment]
After setting {transform: [{translateY: this.position.y}]}, useNativeDriver: true, I still got this error.
 Error: AnimatedValue: Attempting to set value to undefined

**Comment by NTakemori** [comment]
This fix no longer works with the update deprecating super. I plan on working on a fix when I have time.

**Comment by Billwall2020** [comment]
Is there already a solution for this bug? I am currently facing the same issue.

**Comment by NTakemori** [comment]
I redid it with a functional component, I didn't use all the features but it should work without faults: https://github.com/NTakemori/react-native-bottom-drawer
