### ISSUE TITLE
Cannot interact with elements behind drawer (i.e. map)

### ISSUE THREAD

**Issue by impavidum** [jacklein/rn-bottom-drawer#4]
My current code (react-native-maps & rn-bottom-drawer nested in the components shown):

```
{/* Maps Component */}
<JobLocator/>

{/* Jobs Bottom Drawer Component */}
<JobsBottomDrawer navigation={navigation}/>

```

This layers the elements appropriately with the map behind the drawer and the drawer functions as expected, but when I try to interact with the map it is not responsive. I comment out the drawer component and I can interact with the map just fine. Please let me know if this is a known issue or if I have done something incorrectly and I will proceed accordingly. Thanks!

**Comment by impavidum** [comment]
....

**Comment by jacklein** [comment]
Hey sorry for getting back to you a week late. I’m currently laptop-less but I will look into this next week. Apologies

**Comment by jacklein** [comment]
can you post all the code involving the bottom drawer component? a little hard to know what's going on without actually looking at it.

**Comment by shyaniv7** [comment]
Wrap your drawer component with a view that has a higher `zIndex` value than then map

```js
<Map />
<View style={{ zIndex: 2 }}>
  <Drawer navigation={navigation}/>
</View>
```

**Comment by impavidum** [comment]
Closing

**Comment by yasaricli** [comment]
@shyaniv7 If #9  is merge, it can be used as follows.

```
      <BottomDrawer
        containerHeight={100}
        offset={TAB_BAR_HEIGHT}
        animationContainerStyles={{ zIndex: 2 }}
      >
        {this.renderContent()}
      </BottomDrawer>
```

**Comment by impavidum** [comment]
https://github.com/osdnk/react-native-reanimated-bottom-sheet
