### ISSUE TITLE
ScollView does not work within the drawer

### ISSUE THREAD

**Issue by impavidum** [jacklein/rn-bottom-drawer#7]
My code displays the view with the items going off the screen but the view will not scroll. I have tried messing with zIndex and wrapping in views etc with no luck. I have also tried a vertical scroll view and it does not scroll either. Any help is appreciated.

**Comment by impavidum** [comment]
``` <BottomDrawer
        containerHeight={JOBS_LIST_HEIGHT}
        offset={TAB_BAR_HEIGHT}
        startUp={false}
        downDisplay={DOWN_DISPLAY}
        roundedEdges={true}
      >
        <ScrollView horizontal={true}>
          <View style={styles.date}><Text>Today</Text></View>
          <View style={styles.date}><Text>Today</Text></View>
          <View style={styles.date}><Text>Today</Text></View>
          <View style={styles.date}><Text>Today</Text></View>
          <View style={styles.date}><Text>Today</Text></View>
          <View style={styles.date}><Text>Today</Text></View>
          <View style={styles.date}><Text>Today</Text></View>
          <View style={styles.date}><Text>Today</Text></View>
          <View style={styles.date}><Text>Today</Text></View>
        </ScrollView>
      </BottomDrawer>```

**Comment by venzersiz** [comment]
Oh! I got the same problem.

**Comment by loga4** [comment]
add `<TouchableOpacity>` inside scrollview like:

```
<BottomDrawer
        containerHeight={JOBS_LIST_HEIGHT}
        offset={TAB_BAR_HEIGHT}
        startUp={false}
        downDisplay={DOWN_DISPLAY}
        roundedEdges={true}
      >
        <ScrollView horizontal={true}>
<TouchableOpacity>
          <View style={styles.date}><Text>Today</Text></View>
          <View style={styles.date}><Text>Today</Text></View>
          <View style={styles.date}><Text>Today</Text></View>
          <View style={styles.date}><Text>Today</Text></View>
          <View style={styles.date}><Text>Today</Text></View>
          <View style={styles.date}><Text>Today</Text></View>
          <View style={styles.date}><Text>Today</Text></View>
          <View style={styles.date}><Text>Today</Text></View>
          <View style={styles.date}><Text>Today</Text></View>
</TouchableOpacity>
        </ScrollView>
      </BottomDrawer>
```

**Comment by yasaricli** [comment]
@impavidum 
    
    yarn add https://github.com/yasaricli/rn-bottom-drawer.git

``` JS
<BottomDrawer
  containerHeight={420}
  offset={10}
  downDisplay={340}
  roundedEdges={true}
  panResponder={false} // add panResponder to false
  responder={(panHandlers) => {
    return (
        <ScrollView horizontal={true}>
          <TouchableOpacity>
            <View style={styles.date} {...panHandlers}><Text>BottomDrawer</Text></View>
            <View style={styles.date}><Text>Today</Text></View>
            <View style={styles.date}><Text>Today</Text></View>
            <View style={styles.date}><Text>Today</Text></View>
            <View style={styles.date}><Text>Today</Text></View>
            <View style={styles.date}><Text>Today</Text></View>
            <View style={styles.date}><Text>Today</Text></View>
            <View style={styles.date}><Text>Today</Text></View>
            <View style={styles.date}><Text>Today</Text></View>
          </TouchableOpacity>
        </ScrollView>
    )
  }}
/>
```

**Comment by sharpmachine** [comment]
If swipe on the horizontal `ScrollView` to open or close the drawer, it doesn't work.

**Comment by impavidum** [comment]
@sharpmachine https://github.com/osdnk/react-native-reanimated-bottom-sheet

**Comment by Helo3615** [comment]
Still not working for me with `<TouchableOpacity>`

```js
<View>
	<BottomDrawer containerHeight={screenHeight * 0.95}
			  startUp={false}
			  downDisplay={screenHeight * 0.75}
			  shadow={true}
			  style={styles.bottomDrawer}
	>
		<View style={styles.topBar} />
		<ScrollView style={styles.listContainer}>
			<TouchableOpacity activeOpacity={1}>
				{ content.map((item, index) =>
					<ListItem title={item.name}
							leftAvatar={{ source: { uri: item.image } }}
							subtitle={item.description}
							key={index}
							subtitleStyle={styles.listSubtitle}
					/>
				)}
			</TouchableOpacity>
		</ScrollView>
	</BottomDrawer>
</View>
```

**Comment by fsobh** [comment]
How can I add a FlatList instead of a scrollview?

**Comment by haneul512** [comment]
> How can I add a FlatList instead of a scrollview?

Wrapping TouchableOpacity around each renderItem did the trick for me

**Comment by abbasmoosavi** [comment]
> Still not working for me with `<TouchableOpacity>`
> 
> ```js
> <View>
> 	<BottomDrawer containerHeight={screenHeight * 0.95}
> 			  startUp={false}
> 			  downDisplay={screenHeight * 0.75}
> 			  shadow={true}
> 			  style={styles.bottomDrawer}
> 	>
> 		<View style={styles.topBar} />
> 		<ScrollView style={styles.listContainer}>
> 			<TouchableOpacity activeOpacity={1}>
> 				{ content.map((item, index) =>
> 					<ListItem title={item.name}
> 							leftAvatar={{ source: { uri: item.image } }}
> 							subtitle={item.description}
> 							key={index}
> 							subtitleStyle={styles.listSubtitle}
> 					/>
> 				)}
> 			</TouchableOpacity>
> 		</ScrollView>
> 	</BottomDrawer>
> </View>
> ```

Thanks! save my life

**Comment by wl05** [comment]
> @impavidum
> 
> ```
> yarn add https://github.com/yasaricli/rn-bottom-drawer.git
> ```
> 
> ```js
> <BottomDrawer
>   containerHeight={420}
>   offset={10}
>   downDisplay={340}
>   roundedEdges={true}
>   panResponder={false} // add panResponder to false
>   responder={(panHandlers) => {
>     return (
>         <ScrollView horizontal={true}>
>           <TouchableOpacity>
>             <View style={styles.date} {...panHandlers}><Text>BottomDrawer</Text></View>
>             <View style={styles.date}><Text>Today</Text></View>
>             <View style={styles.date}><Text>Today</Text></View>
>             <View style={styles.date}><Text>Today</Text></View>
>             <View style={styles.date}><Text>Today</Text></View>
>             <View style={styles.date}><Text>Today</Text></View>
>             <View style={styles.date}><Text>Today</Text></View>
>             <View style={styles.date}><Text>Today</Text></View>
>             <View style={styles.date}><Text>Today</Text></View>
>           </TouchableOpacity>
>         </ScrollView>
>     )
>   }}
> />
> ```

but how you slide down the drawer?

**Comment by fsobh** [comment]
If You also set the nested ScrollView / FlatList style to have a zIndex : 1 , then the first tap gesture made should be detected by the scrolling view before the bottom sheet. this was my only working work around for nested scroll view in BottomSheet for Android. Still works the same on IOS.

Also, use FlatlLst or ScrollView from react-native-gesture-handler instead of react-native
